// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package autogeneratedProto;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autogeneratedProto_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autogeneratedProto_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autogeneratedProto_EmployeeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autogeneratedProto_EmployeeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\022\022autogeneratedProto\"\236\002\n" +
      "\010Employee\022\014\n\004name\030\001 \002(\t\022\023\n\013employee_id\030\002" +
      " \002(\005\022\025\n\rbuilding_code\030\003 \002(\005\022\016\n\006salary\030\004 " +
      "\002(\002\022\022\n\ndepartment\030\005 \002(\t\0228\n\014floor_number\030" +
      "\006 \002(\0162\".autogeneratedProto.Employee.FLOO" +
      "R\022\026\n\016cafeteria_code\030\007 \001(\005\"b\n\005FLOOR\022\013\n\007FL" +
      "OOR_1\020\001\022\013\n\007FLOOR_2\020\002\022\013\n\007FLOOR_3\020\003\022\013\n\007FLO" +
      "OR_4\020\004\022\013\n\007FLOOR_5\020\005\022\013\n\007FLOOR_6\020\006\022\013\n\007FLOO" +
      "R_7\020\007\"?\n\014EmployeeList\022/\n\temployees\030\001 \003(\013" +
      "2\034.autogeneratedProto.EmployeeB\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_autogeneratedProto_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_autogeneratedProto_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autogeneratedProto_Employee_descriptor,
        new java.lang.String[] { "Name", "EmployeeId", "BuildingCode", "Salary", "Department", "FloorNumber", "CafeteriaCode", });
    internal_static_autogeneratedProto_EmployeeList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_autogeneratedProto_EmployeeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autogeneratedProto_EmployeeList_descriptor,
        new java.lang.String[] { "Employees", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
