// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package autogeneratedProto;

public interface EmployeeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autogeneratedProto.EmployeeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .autogeneratedProto.Employee employees = 1;</code>
   */
  java.util.List<autogeneratedProto.Employee> 
      getEmployeesList();
  /**
   * <code>repeated .autogeneratedProto.Employee employees = 1;</code>
   */
  autogeneratedProto.Employee getEmployees(int index);
  /**
   * <code>repeated .autogeneratedProto.Employee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .autogeneratedProto.Employee employees = 1;</code>
   */
  java.util.List<? extends autogeneratedProto.EmployeeOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .autogeneratedProto.Employee employees = 1;</code>
   */
  autogeneratedProto.EmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
