// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attendance.proto

package autogeneratedProto;

/**
 * Protobuf type {@code autogeneratedProto.Attendance}
 */
public final class Attendance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:autogeneratedProto.Attendance)
    AttendanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Attendance.newBuilder() to construct.
  private Attendance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Attendance() {
    date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Attendance();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Attendance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            employeeId_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              date_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            date_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        date_ = date_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_Attendance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_Attendance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            autogeneratedProto.Attendance.class, autogeneratedProto.Attendance.Builder.class);
  }

  private int bitField0_;
  public static final int EMPLOYEE_ID_FIELD_NUMBER = 1;
  private int employeeId_;
  /**
   * <code>required int32 employee_id = 1;</code>
   * @return Whether the employeeId field is set.
   */
  @java.lang.Override
  public boolean hasEmployeeId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 employee_id = 1;</code>
   * @return The employeeId.
   */
  @java.lang.Override
  public int getEmployeeId() {
    return employeeId_;
  }

  public static final int DATE_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList date_;
  /**
   * <code>repeated string date = 2;</code>
   * @return A list containing the date.
   */
  public com.google.protobuf.ProtocolStringList
      getDateList() {
    return date_;
  }
  /**
   * <code>repeated string date = 2;</code>
   * @return The count of date.
   */
  public int getDateCount() {
    return date_.size();
  }
  /**
   * <code>repeated string date = 2;</code>
   * @param index The index of the element to return.
   * @return The date at the given index.
   */
  public java.lang.String getDate(int index) {
    return date_.get(index);
  }
  /**
   * <code>repeated string date = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the date at the given index.
   */
  public com.google.protobuf.ByteString
      getDateBytes(int index) {
    return date_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasEmployeeId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, employeeId_);
    }
    for (int i = 0; i < date_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, employeeId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < date_.size(); i++) {
        dataSize += computeStringSizeNoTag(date_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDateList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof autogeneratedProto.Attendance)) {
      return super.equals(obj);
    }
    autogeneratedProto.Attendance other = (autogeneratedProto.Attendance) obj;

    if (hasEmployeeId() != other.hasEmployeeId()) return false;
    if (hasEmployeeId()) {
      if (getEmployeeId()
          != other.getEmployeeId()) return false;
    }
    if (!getDateList()
        .equals(other.getDateList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmployeeId()) {
      hash = (37 * hash) + EMPLOYEE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeId();
    }
    if (getDateCount() > 0) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDateList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static autogeneratedProto.Attendance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.Attendance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.Attendance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.Attendance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.Attendance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.Attendance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.Attendance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.Attendance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.Attendance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static autogeneratedProto.Attendance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.Attendance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.Attendance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(autogeneratedProto.Attendance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code autogeneratedProto.Attendance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:autogeneratedProto.Attendance)
      autogeneratedProto.AttendanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_Attendance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_Attendance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              autogeneratedProto.Attendance.class, autogeneratedProto.Attendance.Builder.class);
    }

    // Construct using autogeneratedProto.Attendance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employeeId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_Attendance_descriptor;
    }

    @java.lang.Override
    public autogeneratedProto.Attendance getDefaultInstanceForType() {
      return autogeneratedProto.Attendance.getDefaultInstance();
    }

    @java.lang.Override
    public autogeneratedProto.Attendance build() {
      autogeneratedProto.Attendance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public autogeneratedProto.Attendance buildPartial() {
      autogeneratedProto.Attendance result = new autogeneratedProto.Attendance(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.employeeId_ = employeeId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        date_ = date_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.date_ = date_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof autogeneratedProto.Attendance) {
        return mergeFrom((autogeneratedProto.Attendance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(autogeneratedProto.Attendance other) {
      if (other == autogeneratedProto.Attendance.getDefaultInstance()) return this;
      if (other.hasEmployeeId()) {
        setEmployeeId(other.getEmployeeId());
      }
      if (!other.date_.isEmpty()) {
        if (date_.isEmpty()) {
          date_ = other.date_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDateIsMutable();
          date_.addAll(other.date_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasEmployeeId()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      autogeneratedProto.Attendance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (autogeneratedProto.Attendance) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int employeeId_ ;
    /**
     * <code>required int32 employee_id = 1;</code>
     * @return Whether the employeeId field is set.
     */
    @java.lang.Override
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 employee_id = 1;</code>
     * @return The employeeId.
     */
    @java.lang.Override
    public int getEmployeeId() {
      return employeeId_;
    }
    /**
     * <code>required int32 employee_id = 1;</code>
     * @param value The employeeId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployeeId(int value) {
      bitField0_ |= 0x00000001;
      employeeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 employee_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployeeId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      employeeId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDateIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        date_ = new com.google.protobuf.LazyStringArrayList(date_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string date = 2;</code>
     * @return A list containing the date.
     */
    public com.google.protobuf.ProtocolStringList
        getDateList() {
      return date_.getUnmodifiableView();
    }
    /**
     * <code>repeated string date = 2;</code>
     * @return The count of date.
     */
    public int getDateCount() {
      return date_.size();
    }
    /**
     * <code>repeated string date = 2;</code>
     * @param index The index of the element to return.
     * @return The date at the given index.
     */
    public java.lang.String getDate(int index) {
      return date_.get(index);
    }
    /**
     * <code>repeated string date = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the date at the given index.
     */
    public com.google.protobuf.ByteString
        getDateBytes(int index) {
      return date_.getByteString(index);
    }
    /**
     * <code>repeated string date = 2;</code>
     * @param index The index to set the value at.
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDateIsMutable();
      date_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string date = 2;</code>
     * @param value The date to add.
     * @return This builder for chaining.
     */
    public Builder addDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDateIsMutable();
      date_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string date = 2;</code>
     * @param values The date to add.
     * @return This builder for chaining.
     */
    public Builder addAllDate(
        java.lang.Iterable<java.lang.String> values) {
      ensureDateIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, date_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string date = 2;</code>
     * @param value The bytes of the date to add.
     * @return This builder for chaining.
     */
    public Builder addDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDateIsMutable();
      date_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:autogeneratedProto.Attendance)
  }

  // @@protoc_insertion_point(class_scope:autogeneratedProto.Attendance)
  private static final autogeneratedProto.Attendance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new autogeneratedProto.Attendance();
  }

  public static autogeneratedProto.Attendance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Attendance>
      PARSER = new com.google.protobuf.AbstractParser<Attendance>() {
    @java.lang.Override
    public Attendance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Attendance(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Attendance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Attendance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public autogeneratedProto.Attendance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

