// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attendance.proto

package autogeneratedProto;

/**
 * Protobuf type {@code autogeneratedProto.AttendanceList}
 */
public final class AttendanceList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:autogeneratedProto.AttendanceList)
    AttendanceListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AttendanceList.newBuilder() to construct.
  private AttendanceList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AttendanceList() {
    attendance_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AttendanceList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AttendanceList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              attendance_ = new java.util.ArrayList<autogeneratedProto.Attendance>();
              mutable_bitField0_ |= 0x00000001;
            }
            attendance_.add(
                input.readMessage(autogeneratedProto.Attendance.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        attendance_ = java.util.Collections.unmodifiableList(attendance_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_AttendanceList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_AttendanceList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            autogeneratedProto.AttendanceList.class, autogeneratedProto.AttendanceList.Builder.class);
  }

  public static final int ATTENDANCE_FIELD_NUMBER = 1;
  private java.util.List<autogeneratedProto.Attendance> attendance_;
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  @java.lang.Override
  public java.util.List<autogeneratedProto.Attendance> getAttendanceList() {
    return attendance_;
  }
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends autogeneratedProto.AttendanceOrBuilder> 
      getAttendanceOrBuilderList() {
    return attendance_;
  }
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  @java.lang.Override
  public int getAttendanceCount() {
    return attendance_.size();
  }
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  @java.lang.Override
  public autogeneratedProto.Attendance getAttendance(int index) {
    return attendance_.get(index);
  }
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  @java.lang.Override
  public autogeneratedProto.AttendanceOrBuilder getAttendanceOrBuilder(
      int index) {
    return attendance_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getAttendanceCount(); i++) {
      if (!getAttendance(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < attendance_.size(); i++) {
      output.writeMessage(1, attendance_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < attendance_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, attendance_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof autogeneratedProto.AttendanceList)) {
      return super.equals(obj);
    }
    autogeneratedProto.AttendanceList other = (autogeneratedProto.AttendanceList) obj;

    if (!getAttendanceList()
        .equals(other.getAttendanceList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAttendanceCount() > 0) {
      hash = (37 * hash) + ATTENDANCE_FIELD_NUMBER;
      hash = (53 * hash) + getAttendanceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static autogeneratedProto.AttendanceList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.AttendanceList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.AttendanceList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.AttendanceList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static autogeneratedProto.AttendanceList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.AttendanceList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(autogeneratedProto.AttendanceList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code autogeneratedProto.AttendanceList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:autogeneratedProto.AttendanceList)
      autogeneratedProto.AttendanceListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_AttendanceList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_AttendanceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              autogeneratedProto.AttendanceList.class, autogeneratedProto.AttendanceList.Builder.class);
    }

    // Construct using autogeneratedProto.AttendanceList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttendanceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (attendanceBuilder_ == null) {
        attendance_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        attendanceBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return autogeneratedProto.AttendanceOuterClass.internal_static_autogeneratedProto_AttendanceList_descriptor;
    }

    @java.lang.Override
    public autogeneratedProto.AttendanceList getDefaultInstanceForType() {
      return autogeneratedProto.AttendanceList.getDefaultInstance();
    }

    @java.lang.Override
    public autogeneratedProto.AttendanceList build() {
      autogeneratedProto.AttendanceList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public autogeneratedProto.AttendanceList buildPartial() {
      autogeneratedProto.AttendanceList result = new autogeneratedProto.AttendanceList(this);
      int from_bitField0_ = bitField0_;
      if (attendanceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          attendance_ = java.util.Collections.unmodifiableList(attendance_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.attendance_ = attendance_;
      } else {
        result.attendance_ = attendanceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof autogeneratedProto.AttendanceList) {
        return mergeFrom((autogeneratedProto.AttendanceList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(autogeneratedProto.AttendanceList other) {
      if (other == autogeneratedProto.AttendanceList.getDefaultInstance()) return this;
      if (attendanceBuilder_ == null) {
        if (!other.attendance_.isEmpty()) {
          if (attendance_.isEmpty()) {
            attendance_ = other.attendance_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAttendanceIsMutable();
            attendance_.addAll(other.attendance_);
          }
          onChanged();
        }
      } else {
        if (!other.attendance_.isEmpty()) {
          if (attendanceBuilder_.isEmpty()) {
            attendanceBuilder_.dispose();
            attendanceBuilder_ = null;
            attendance_ = other.attendance_;
            bitField0_ = (bitField0_ & ~0x00000001);
            attendanceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttendanceFieldBuilder() : null;
          } else {
            attendanceBuilder_.addAllMessages(other.attendance_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getAttendanceCount(); i++) {
        if (!getAttendance(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      autogeneratedProto.AttendanceList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (autogeneratedProto.AttendanceList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<autogeneratedProto.Attendance> attendance_ =
      java.util.Collections.emptyList();
    private void ensureAttendanceIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        attendance_ = new java.util.ArrayList<autogeneratedProto.Attendance>(attendance_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        autogeneratedProto.Attendance, autogeneratedProto.Attendance.Builder, autogeneratedProto.AttendanceOrBuilder> attendanceBuilder_;

    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public java.util.List<autogeneratedProto.Attendance> getAttendanceList() {
      if (attendanceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attendance_);
      } else {
        return attendanceBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public int getAttendanceCount() {
      if (attendanceBuilder_ == null) {
        return attendance_.size();
      } else {
        return attendanceBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public autogeneratedProto.Attendance getAttendance(int index) {
      if (attendanceBuilder_ == null) {
        return attendance_.get(index);
      } else {
        return attendanceBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder setAttendance(
        int index, autogeneratedProto.Attendance value) {
      if (attendanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttendanceIsMutable();
        attendance_.set(index, value);
        onChanged();
      } else {
        attendanceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder setAttendance(
        int index, autogeneratedProto.Attendance.Builder builderForValue) {
      if (attendanceBuilder_ == null) {
        ensureAttendanceIsMutable();
        attendance_.set(index, builderForValue.build());
        onChanged();
      } else {
        attendanceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder addAttendance(autogeneratedProto.Attendance value) {
      if (attendanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttendanceIsMutable();
        attendance_.add(value);
        onChanged();
      } else {
        attendanceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder addAttendance(
        int index, autogeneratedProto.Attendance value) {
      if (attendanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttendanceIsMutable();
        attendance_.add(index, value);
        onChanged();
      } else {
        attendanceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder addAttendance(
        autogeneratedProto.Attendance.Builder builderForValue) {
      if (attendanceBuilder_ == null) {
        ensureAttendanceIsMutable();
        attendance_.add(builderForValue.build());
        onChanged();
      } else {
        attendanceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder addAttendance(
        int index, autogeneratedProto.Attendance.Builder builderForValue) {
      if (attendanceBuilder_ == null) {
        ensureAttendanceIsMutable();
        attendance_.add(index, builderForValue.build());
        onChanged();
      } else {
        attendanceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder addAllAttendance(
        java.lang.Iterable<? extends autogeneratedProto.Attendance> values) {
      if (attendanceBuilder_ == null) {
        ensureAttendanceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attendance_);
        onChanged();
      } else {
        attendanceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder clearAttendance() {
      if (attendanceBuilder_ == null) {
        attendance_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        attendanceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public Builder removeAttendance(int index) {
      if (attendanceBuilder_ == null) {
        ensureAttendanceIsMutable();
        attendance_.remove(index);
        onChanged();
      } else {
        attendanceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public autogeneratedProto.Attendance.Builder getAttendanceBuilder(
        int index) {
      return getAttendanceFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public autogeneratedProto.AttendanceOrBuilder getAttendanceOrBuilder(
        int index) {
      if (attendanceBuilder_ == null) {
        return attendance_.get(index);  } else {
        return attendanceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public java.util.List<? extends autogeneratedProto.AttendanceOrBuilder> 
         getAttendanceOrBuilderList() {
      if (attendanceBuilder_ != null) {
        return attendanceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attendance_);
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public autogeneratedProto.Attendance.Builder addAttendanceBuilder() {
      return getAttendanceFieldBuilder().addBuilder(
          autogeneratedProto.Attendance.getDefaultInstance());
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public autogeneratedProto.Attendance.Builder addAttendanceBuilder(
        int index) {
      return getAttendanceFieldBuilder().addBuilder(
          index, autogeneratedProto.Attendance.getDefaultInstance());
    }
    /**
     * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
     */
    public java.util.List<autogeneratedProto.Attendance.Builder> 
         getAttendanceBuilderList() {
      return getAttendanceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        autogeneratedProto.Attendance, autogeneratedProto.Attendance.Builder, autogeneratedProto.AttendanceOrBuilder> 
        getAttendanceFieldBuilder() {
      if (attendanceBuilder_ == null) {
        attendanceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            autogeneratedProto.Attendance, autogeneratedProto.Attendance.Builder, autogeneratedProto.AttendanceOrBuilder>(
                attendance_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        attendance_ = null;
      }
      return attendanceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:autogeneratedProto.AttendanceList)
  }

  // @@protoc_insertion_point(class_scope:autogeneratedProto.AttendanceList)
  private static final autogeneratedProto.AttendanceList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new autogeneratedProto.AttendanceList();
  }

  public static autogeneratedProto.AttendanceList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AttendanceList>
      PARSER = new com.google.protobuf.AbstractParser<AttendanceList>() {
    @java.lang.Override
    public AttendanceList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AttendanceList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AttendanceList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttendanceList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public autogeneratedProto.AttendanceList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

