// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attendance.proto

package autogeneratedProto;

public interface AttendanceListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autogeneratedProto.AttendanceList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  java.util.List<autogeneratedProto.Attendance> 
      getAttendanceList();
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  autogeneratedProto.Attendance getAttendance(int index);
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  int getAttendanceCount();
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  java.util.List<? extends autogeneratedProto.AttendanceOrBuilder> 
      getAttendanceOrBuilderList();
  /**
   * <code>repeated .autogeneratedProto.Attendance attendance = 1;</code>
   */
  autogeneratedProto.AttendanceOrBuilder getAttendanceOrBuilder(
      int index);
}
