// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attendance.proto

package autogeneratedProto;

public final class AttendanceOuterClass {
  private AttendanceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autogeneratedProto_Attendance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autogeneratedProto_Attendance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autogeneratedProto_AttendanceList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autogeneratedProto_AttendanceList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Attendance.proto\022\022autogeneratedProto\"/" +
      "\n\nAttendance\022\023\n\013employee_id\030\001 \002(\005\022\014\n\004dat" +
      "e\030\002 \003(\t\"D\n\016AttendanceList\0222\n\nattendance\030" +
      "\001 \003(\0132\036.autogeneratedProto.AttendanceB\002P" +
      "\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_autogeneratedProto_Attendance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_autogeneratedProto_Attendance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autogeneratedProto_Attendance_descriptor,
        new java.lang.String[] { "EmployeeId", "Date", });
    internal_static_autogeneratedProto_AttendanceList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_autogeneratedProto_AttendanceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autogeneratedProto_AttendanceList_descriptor,
        new java.lang.String[] { "Attendance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
