// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attendance.proto

package autogeneratedProto;

public interface AttendanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autogeneratedProto.Attendance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 employee_id = 1;</code>
   * @return Whether the employeeId field is set.
   */
  boolean hasEmployeeId();
  /**
   * <code>required int32 employee_id = 1;</code>
   * @return The employeeId.
   */
  int getEmployeeId();

  /**
   * <code>repeated string date = 2;</code>
   * @return A list containing the date.
   */
  java.util.List<java.lang.String>
      getDateList();
  /**
   * <code>repeated string date = 2;</code>
   * @return The count of date.
   */
  int getDateCount();
  /**
   * <code>repeated string date = 2;</code>
   * @param index The index of the element to return.
   * @return The date at the given index.
   */
  java.lang.String getDate(int index);
  /**
   * <code>repeated string date = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the date at the given index.
   */
  com.google.protobuf.ByteString
      getDateBytes(int index);
}
