// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Building.proto

package autogeneratedProto;

public interface BuildingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autogeneratedProto.Building)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 building_code = 1;</code>
   * @return Whether the buildingCode field is set.
   */
  boolean hasBuildingCode();
  /**
   * <code>required int32 building_code = 1;</code>
   * @return The buildingCode.
   */
  int getBuildingCode();

  /**
   * <code>required int32 total_floor = 2;</code>
   * @return Whether the totalFloor field is set.
   */
  boolean hasTotalFloor();
  /**
   * <code>required int32 total_floor = 2;</code>
   * @return The totalFloor.
   */
  int getTotalFloor();

  /**
   * <code>required int32 number_of_companies = 3;</code>
   * @return Whether the numberOfCompanies field is set.
   */
  boolean hasNumberOfCompanies();
  /**
   * <code>required int32 number_of_companies = 3;</code>
   * @return The numberOfCompanies.
   */
  int getNumberOfCompanies();

  /**
   * <code>required int32 cafeteria_code = 4;</code>
   * @return Whether the cafeteriaCode field is set.
   */
  boolean hasCafeteriaCode();
  /**
   * <code>required int32 cafeteria_code = 4;</code>
   * @return The cafeteriaCode.
   */
  int getCafeteriaCode();
}
