// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Building.proto

package autogeneratedProto;

public interface BuildingListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autogeneratedProto.BuildingList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  java.util.List<autogeneratedProto.Building> 
      getBuildingList();
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  autogeneratedProto.Building getBuilding(int index);
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  int getBuildingCount();
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  java.util.List<? extends autogeneratedProto.BuildingOrBuilder> 
      getBuildingOrBuilderList();
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  autogeneratedProto.BuildingOrBuilder getBuildingOrBuilder(
      int index);
}
