// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Building.proto

package autogeneratedProto;

/**
 * Protobuf type {@code autogeneratedProto.BuildingList}
 */
public final class BuildingList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:autogeneratedProto.BuildingList)
    BuildingListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BuildingList.newBuilder() to construct.
  private BuildingList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BuildingList() {
    building_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BuildingList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BuildingList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              building_ = new java.util.ArrayList<autogeneratedProto.Building>();
              mutable_bitField0_ |= 0x00000001;
            }
            building_.add(
                input.readMessage(autogeneratedProto.Building.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        building_ = java.util.Collections.unmodifiableList(building_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return autogeneratedProto.BuildingOuterClass.internal_static_autogeneratedProto_BuildingList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return autogeneratedProto.BuildingOuterClass.internal_static_autogeneratedProto_BuildingList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            autogeneratedProto.BuildingList.class, autogeneratedProto.BuildingList.Builder.class);
  }

  public static final int BUILDING_FIELD_NUMBER = 1;
  private java.util.List<autogeneratedProto.Building> building_;
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  @java.lang.Override
  public java.util.List<autogeneratedProto.Building> getBuildingList() {
    return building_;
  }
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends autogeneratedProto.BuildingOrBuilder> 
      getBuildingOrBuilderList() {
    return building_;
  }
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  @java.lang.Override
  public int getBuildingCount() {
    return building_.size();
  }
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  @java.lang.Override
  public autogeneratedProto.Building getBuilding(int index) {
    return building_.get(index);
  }
  /**
   * <code>repeated .autogeneratedProto.Building building = 1;</code>
   */
  @java.lang.Override
  public autogeneratedProto.BuildingOrBuilder getBuildingOrBuilder(
      int index) {
    return building_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getBuildingCount(); i++) {
      if (!getBuilding(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < building_.size(); i++) {
      output.writeMessage(1, building_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < building_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, building_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof autogeneratedProto.BuildingList)) {
      return super.equals(obj);
    }
    autogeneratedProto.BuildingList other = (autogeneratedProto.BuildingList) obj;

    if (!getBuildingList()
        .equals(other.getBuildingList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBuildingCount() > 0) {
      hash = (37 * hash) + BUILDING_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static autogeneratedProto.BuildingList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.BuildingList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.BuildingList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.BuildingList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static autogeneratedProto.BuildingList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.BuildingList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(autogeneratedProto.BuildingList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code autogeneratedProto.BuildingList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:autogeneratedProto.BuildingList)
      autogeneratedProto.BuildingListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return autogeneratedProto.BuildingOuterClass.internal_static_autogeneratedProto_BuildingList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return autogeneratedProto.BuildingOuterClass.internal_static_autogeneratedProto_BuildingList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              autogeneratedProto.BuildingList.class, autogeneratedProto.BuildingList.Builder.class);
    }

    // Construct using autogeneratedProto.BuildingList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBuildingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (buildingBuilder_ == null) {
        building_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        buildingBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return autogeneratedProto.BuildingOuterClass.internal_static_autogeneratedProto_BuildingList_descriptor;
    }

    @java.lang.Override
    public autogeneratedProto.BuildingList getDefaultInstanceForType() {
      return autogeneratedProto.BuildingList.getDefaultInstance();
    }

    @java.lang.Override
    public autogeneratedProto.BuildingList build() {
      autogeneratedProto.BuildingList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public autogeneratedProto.BuildingList buildPartial() {
      autogeneratedProto.BuildingList result = new autogeneratedProto.BuildingList(this);
      int from_bitField0_ = bitField0_;
      if (buildingBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          building_ = java.util.Collections.unmodifiableList(building_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.building_ = building_;
      } else {
        result.building_ = buildingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof autogeneratedProto.BuildingList) {
        return mergeFrom((autogeneratedProto.BuildingList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(autogeneratedProto.BuildingList other) {
      if (other == autogeneratedProto.BuildingList.getDefaultInstance()) return this;
      if (buildingBuilder_ == null) {
        if (!other.building_.isEmpty()) {
          if (building_.isEmpty()) {
            building_ = other.building_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBuildingIsMutable();
            building_.addAll(other.building_);
          }
          onChanged();
        }
      } else {
        if (!other.building_.isEmpty()) {
          if (buildingBuilder_.isEmpty()) {
            buildingBuilder_.dispose();
            buildingBuilder_ = null;
            building_ = other.building_;
            bitField0_ = (bitField0_ & ~0x00000001);
            buildingBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBuildingFieldBuilder() : null;
          } else {
            buildingBuilder_.addAllMessages(other.building_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getBuildingCount(); i++) {
        if (!getBuilding(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      autogeneratedProto.BuildingList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (autogeneratedProto.BuildingList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<autogeneratedProto.Building> building_ =
      java.util.Collections.emptyList();
    private void ensureBuildingIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        building_ = new java.util.ArrayList<autogeneratedProto.Building>(building_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        autogeneratedProto.Building, autogeneratedProto.Building.Builder, autogeneratedProto.BuildingOrBuilder> buildingBuilder_;

    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public java.util.List<autogeneratedProto.Building> getBuildingList() {
      if (buildingBuilder_ == null) {
        return java.util.Collections.unmodifiableList(building_);
      } else {
        return buildingBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public int getBuildingCount() {
      if (buildingBuilder_ == null) {
        return building_.size();
      } else {
        return buildingBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public autogeneratedProto.Building getBuilding(int index) {
      if (buildingBuilder_ == null) {
        return building_.get(index);
      } else {
        return buildingBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder setBuilding(
        int index, autogeneratedProto.Building value) {
      if (buildingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuildingIsMutable();
        building_.set(index, value);
        onChanged();
      } else {
        buildingBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder setBuilding(
        int index, autogeneratedProto.Building.Builder builderForValue) {
      if (buildingBuilder_ == null) {
        ensureBuildingIsMutable();
        building_.set(index, builderForValue.build());
        onChanged();
      } else {
        buildingBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder addBuilding(autogeneratedProto.Building value) {
      if (buildingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuildingIsMutable();
        building_.add(value);
        onChanged();
      } else {
        buildingBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder addBuilding(
        int index, autogeneratedProto.Building value) {
      if (buildingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuildingIsMutable();
        building_.add(index, value);
        onChanged();
      } else {
        buildingBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder addBuilding(
        autogeneratedProto.Building.Builder builderForValue) {
      if (buildingBuilder_ == null) {
        ensureBuildingIsMutable();
        building_.add(builderForValue.build());
        onChanged();
      } else {
        buildingBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder addBuilding(
        int index, autogeneratedProto.Building.Builder builderForValue) {
      if (buildingBuilder_ == null) {
        ensureBuildingIsMutable();
        building_.add(index, builderForValue.build());
        onChanged();
      } else {
        buildingBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder addAllBuilding(
        java.lang.Iterable<? extends autogeneratedProto.Building> values) {
      if (buildingBuilder_ == null) {
        ensureBuildingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, building_);
        onChanged();
      } else {
        buildingBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder clearBuilding() {
      if (buildingBuilder_ == null) {
        building_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        buildingBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public Builder removeBuilding(int index) {
      if (buildingBuilder_ == null) {
        ensureBuildingIsMutable();
        building_.remove(index);
        onChanged();
      } else {
        buildingBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public autogeneratedProto.Building.Builder getBuildingBuilder(
        int index) {
      return getBuildingFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public autogeneratedProto.BuildingOrBuilder getBuildingOrBuilder(
        int index) {
      if (buildingBuilder_ == null) {
        return building_.get(index);  } else {
        return buildingBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public java.util.List<? extends autogeneratedProto.BuildingOrBuilder> 
         getBuildingOrBuilderList() {
      if (buildingBuilder_ != null) {
        return buildingBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(building_);
      }
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public autogeneratedProto.Building.Builder addBuildingBuilder() {
      return getBuildingFieldBuilder().addBuilder(
          autogeneratedProto.Building.getDefaultInstance());
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public autogeneratedProto.Building.Builder addBuildingBuilder(
        int index) {
      return getBuildingFieldBuilder().addBuilder(
          index, autogeneratedProto.Building.getDefaultInstance());
    }
    /**
     * <code>repeated .autogeneratedProto.Building building = 1;</code>
     */
    public java.util.List<autogeneratedProto.Building.Builder> 
         getBuildingBuilderList() {
      return getBuildingFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        autogeneratedProto.Building, autogeneratedProto.Building.Builder, autogeneratedProto.BuildingOrBuilder> 
        getBuildingFieldBuilder() {
      if (buildingBuilder_ == null) {
        buildingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            autogeneratedProto.Building, autogeneratedProto.Building.Builder, autogeneratedProto.BuildingOrBuilder>(
                building_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        building_ = null;
      }
      return buildingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:autogeneratedProto.BuildingList)
  }

  // @@protoc_insertion_point(class_scope:autogeneratedProto.BuildingList)
  private static final autogeneratedProto.BuildingList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new autogeneratedProto.BuildingList();
  }

  public static autogeneratedProto.BuildingList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<BuildingList>
      PARSER = new com.google.protobuf.AbstractParser<BuildingList>() {
    @java.lang.Override
    public BuildingList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BuildingList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BuildingList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BuildingList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public autogeneratedProto.BuildingList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

