// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Building.proto

package autogeneratedProto;

public final class BuildingOuterClass {
  private BuildingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autogeneratedProto_Building_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autogeneratedProto_Building_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autogeneratedProto_BuildingList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autogeneratedProto_BuildingList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Building.proto\022\022autogeneratedProto\"k\n\010" +
      "Building\022\025\n\rbuilding_code\030\001 \002(\005\022\023\n\013total" +
      "_floor\030\002 \002(\005\022\033\n\023number_of_companies\030\003 \002(" +
      "\005\022\026\n\016cafeteria_code\030\004 \002(\005\">\n\014BuildingLis" +
      "t\022.\n\010building\030\001 \003(\0132\034.autogeneratedProto" +
      ".BuildingB\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_autogeneratedProto_Building_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_autogeneratedProto_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autogeneratedProto_Building_descriptor,
        new java.lang.String[] { "BuildingCode", "TotalFloor", "NumberOfCompanies", "CafeteriaCode", });
    internal_static_autogeneratedProto_BuildingList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_autogeneratedProto_BuildingList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autogeneratedProto_BuildingList_descriptor,
        new java.lang.String[] { "Building", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
