// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package autogeneratedProto;

/**
 * Protobuf type {@code autogeneratedProto.Employee}
 */
public final class Employee extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:autogeneratedProto.Employee)
    EmployeeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Employee.newBuilder() to construct.
  private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Employee() {
    name_ = "";
    department_ = "";
    floorNumber_ = 1;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Employee();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Employee(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            name_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            employeeId_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            buildingCode_ = input.readInt32();
            break;
          }
          case 37: {
            bitField0_ |= 0x00000008;
            salary_ = input.readFloat();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            department_ = bs;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            autogeneratedProto.Employee.FLOOR value = autogeneratedProto.Employee.FLOOR.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              floorNumber_ = rawValue;
            }
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            cafeteriaCode_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return autogeneratedProto.EmployeeOuterClass.internal_static_autogeneratedProto_Employee_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return autogeneratedProto.EmployeeOuterClass.internal_static_autogeneratedProto_Employee_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            autogeneratedProto.Employee.class, autogeneratedProto.Employee.Builder.class);
  }

  /**
   * Protobuf enum {@code autogeneratedProto.Employee.FLOOR}
   */
  public enum FLOOR
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FLOOR_1 = 1;</code>
     */
    FLOOR_1(1),
    /**
     * <code>FLOOR_2 = 2;</code>
     */
    FLOOR_2(2),
    /**
     * <code>FLOOR_3 = 3;</code>
     */
    FLOOR_3(3),
    /**
     * <code>FLOOR_4 = 4;</code>
     */
    FLOOR_4(4),
    /**
     * <code>FLOOR_5 = 5;</code>
     */
    FLOOR_5(5),
    /**
     * <code>FLOOR_6 = 6;</code>
     */
    FLOOR_6(6),
    /**
     * <code>FLOOR_7 = 7;</code>
     */
    FLOOR_7(7),
    ;

    /**
     * <code>FLOOR_1 = 1;</code>
     */
    public static final int FLOOR_1_VALUE = 1;
    /**
     * <code>FLOOR_2 = 2;</code>
     */
    public static final int FLOOR_2_VALUE = 2;
    /**
     * <code>FLOOR_3 = 3;</code>
     */
    public static final int FLOOR_3_VALUE = 3;
    /**
     * <code>FLOOR_4 = 4;</code>
     */
    public static final int FLOOR_4_VALUE = 4;
    /**
     * <code>FLOOR_5 = 5;</code>
     */
    public static final int FLOOR_5_VALUE = 5;
    /**
     * <code>FLOOR_6 = 6;</code>
     */
    public static final int FLOOR_6_VALUE = 6;
    /**
     * <code>FLOOR_7 = 7;</code>
     */
    public static final int FLOOR_7_VALUE = 7;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FLOOR valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FLOOR forNumber(int value) {
      switch (value) {
        case 1: return FLOOR_1;
        case 2: return FLOOR_2;
        case 3: return FLOOR_3;
        case 4: return FLOOR_4;
        case 5: return FLOOR_5;
        case 6: return FLOOR_6;
        case 7: return FLOOR_7;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FLOOR>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FLOOR> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FLOOR>() {
            public FLOOR findValueByNumber(int number) {
              return FLOOR.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return autogeneratedProto.Employee.getDescriptor().getEnumTypes().get(0);
    }

    private static final FLOOR[] VALUES = values();

    public static FLOOR valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FLOOR(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:autogeneratedProto.Employee.FLOOR)
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYEE_ID_FIELD_NUMBER = 2;
  private int employeeId_;
  /**
   * <code>required int32 employee_id = 2;</code>
   * @return Whether the employeeId field is set.
   */
  @java.lang.Override
  public boolean hasEmployeeId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int32 employee_id = 2;</code>
   * @return The employeeId.
   */
  @java.lang.Override
  public int getEmployeeId() {
    return employeeId_;
  }

  public static final int BUILDING_CODE_FIELD_NUMBER = 3;
  private int buildingCode_;
  /**
   * <code>required int32 building_code = 3;</code>
   * @return Whether the buildingCode field is set.
   */
  @java.lang.Override
  public boolean hasBuildingCode() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int32 building_code = 3;</code>
   * @return The buildingCode.
   */
  @java.lang.Override
  public int getBuildingCode() {
    return buildingCode_;
  }

  public static final int SALARY_FIELD_NUMBER = 4;
  private float salary_;
  /**
   * <code>required float salary = 4;</code>
   * @return Whether the salary field is set.
   */
  @java.lang.Override
  public boolean hasSalary() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required float salary = 4;</code>
   * @return The salary.
   */
  @java.lang.Override
  public float getSalary() {
    return salary_;
  }

  public static final int DEPARTMENT_FIELD_NUMBER = 5;
  private volatile java.lang.Object department_;
  /**
   * <code>required string department = 5;</code>
   * @return Whether the department field is set.
   */
  @java.lang.Override
  public boolean hasDepartment() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required string department = 5;</code>
   * @return The department.
   */
  @java.lang.Override
  public java.lang.String getDepartment() {
    java.lang.Object ref = department_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        department_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string department = 5;</code>
   * @return The bytes for department.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDepartmentBytes() {
    java.lang.Object ref = department_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      department_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOOR_NUMBER_FIELD_NUMBER = 6;
  private int floorNumber_;
  /**
   * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
   * @return Whether the floorNumber field is set.
   */
  @java.lang.Override public boolean hasFloorNumber() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
   * @return The floorNumber.
   */
  @java.lang.Override public autogeneratedProto.Employee.FLOOR getFloorNumber() {
    @SuppressWarnings("deprecation")
    autogeneratedProto.Employee.FLOOR result = autogeneratedProto.Employee.FLOOR.valueOf(floorNumber_);
    return result == null ? autogeneratedProto.Employee.FLOOR.FLOOR_1 : result;
  }

  public static final int CAFETERIA_CODE_FIELD_NUMBER = 7;
  private int cafeteriaCode_;
  /**
   * <code>optional int32 cafeteria_code = 7;</code>
   * @return Whether the cafeteriaCode field is set.
   */
  @java.lang.Override
  public boolean hasCafeteriaCode() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int32 cafeteria_code = 7;</code>
   * @return The cafeteriaCode.
   */
  @java.lang.Override
  public int getCafeteriaCode() {
    return cafeteriaCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasEmployeeId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBuildingCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSalary()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDepartment()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasFloorNumber()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, employeeId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, buildingCode_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeFloat(4, salary_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, department_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeEnum(6, floorNumber_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, cafeteriaCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, employeeId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, buildingCode_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, salary_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, department_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, floorNumber_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, cafeteriaCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof autogeneratedProto.Employee)) {
      return super.equals(obj);
    }
    autogeneratedProto.Employee other = (autogeneratedProto.Employee) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasEmployeeId() != other.hasEmployeeId()) return false;
    if (hasEmployeeId()) {
      if (getEmployeeId()
          != other.getEmployeeId()) return false;
    }
    if (hasBuildingCode() != other.hasBuildingCode()) return false;
    if (hasBuildingCode()) {
      if (getBuildingCode()
          != other.getBuildingCode()) return false;
    }
    if (hasSalary() != other.hasSalary()) return false;
    if (hasSalary()) {
      if (java.lang.Float.floatToIntBits(getSalary())
          != java.lang.Float.floatToIntBits(
              other.getSalary())) return false;
    }
    if (hasDepartment() != other.hasDepartment()) return false;
    if (hasDepartment()) {
      if (!getDepartment()
          .equals(other.getDepartment())) return false;
    }
    if (hasFloorNumber() != other.hasFloorNumber()) return false;
    if (hasFloorNumber()) {
      if (floorNumber_ != other.floorNumber_) return false;
    }
    if (hasCafeteriaCode() != other.hasCafeteriaCode()) return false;
    if (hasCafeteriaCode()) {
      if (getCafeteriaCode()
          != other.getCafeteriaCode()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasEmployeeId()) {
      hash = (37 * hash) + EMPLOYEE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeId();
    }
    if (hasBuildingCode()) {
      hash = (37 * hash) + BUILDING_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingCode();
    }
    if (hasSalary()) {
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSalary());
    }
    if (hasDepartment()) {
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartment().hashCode();
    }
    if (hasFloorNumber()) {
      hash = (37 * hash) + FLOOR_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + floorNumber_;
    }
    if (hasCafeteriaCode()) {
      hash = (37 * hash) + CAFETERIA_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCafeteriaCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static autogeneratedProto.Employee parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.Employee parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.Employee parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.Employee parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.Employee parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static autogeneratedProto.Employee parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static autogeneratedProto.Employee parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.Employee parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.Employee parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static autogeneratedProto.Employee parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static autogeneratedProto.Employee parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static autogeneratedProto.Employee parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(autogeneratedProto.Employee prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code autogeneratedProto.Employee}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:autogeneratedProto.Employee)
      autogeneratedProto.EmployeeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return autogeneratedProto.EmployeeOuterClass.internal_static_autogeneratedProto_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return autogeneratedProto.EmployeeOuterClass.internal_static_autogeneratedProto_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              autogeneratedProto.Employee.class, autogeneratedProto.Employee.Builder.class);
    }

    // Construct using autogeneratedProto.Employee.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      employeeId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      buildingCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      salary_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000008);
      department_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      floorNumber_ = 1;
      bitField0_ = (bitField0_ & ~0x00000020);
      cafeteriaCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return autogeneratedProto.EmployeeOuterClass.internal_static_autogeneratedProto_Employee_descriptor;
    }

    @java.lang.Override
    public autogeneratedProto.Employee getDefaultInstanceForType() {
      return autogeneratedProto.Employee.getDefaultInstance();
    }

    @java.lang.Override
    public autogeneratedProto.Employee build() {
      autogeneratedProto.Employee result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public autogeneratedProto.Employee buildPartial() {
      autogeneratedProto.Employee result = new autogeneratedProto.Employee(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.employeeId_ = employeeId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.buildingCode_ = buildingCode_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.salary_ = salary_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.department_ = department_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.floorNumber_ = floorNumber_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.cafeteriaCode_ = cafeteriaCode_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof autogeneratedProto.Employee) {
        return mergeFrom((autogeneratedProto.Employee)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(autogeneratedProto.Employee other) {
      if (other == autogeneratedProto.Employee.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasEmployeeId()) {
        setEmployeeId(other.getEmployeeId());
      }
      if (other.hasBuildingCode()) {
        setBuildingCode(other.getBuildingCode());
      }
      if (other.hasSalary()) {
        setSalary(other.getSalary());
      }
      if (other.hasDepartment()) {
        bitField0_ |= 0x00000010;
        department_ = other.department_;
        onChanged();
      }
      if (other.hasFloorNumber()) {
        setFloorNumber(other.getFloorNumber());
      }
      if (other.hasCafeteriaCode()) {
        setCafeteriaCode(other.getCafeteriaCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasName()) {
        return false;
      }
      if (!hasEmployeeId()) {
        return false;
      }
      if (!hasBuildingCode()) {
        return false;
      }
      if (!hasSalary()) {
        return false;
      }
      if (!hasDepartment()) {
        return false;
      }
      if (!hasFloorNumber()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      autogeneratedProto.Employee parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (autogeneratedProto.Employee) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private int employeeId_ ;
    /**
     * <code>required int32 employee_id = 2;</code>
     * @return Whether the employeeId field is set.
     */
    @java.lang.Override
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 employee_id = 2;</code>
     * @return The employeeId.
     */
    @java.lang.Override
    public int getEmployeeId() {
      return employeeId_;
    }
    /**
     * <code>required int32 employee_id = 2;</code>
     * @param value The employeeId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployeeId(int value) {
      bitField0_ |= 0x00000002;
      employeeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 employee_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployeeId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      employeeId_ = 0;
      onChanged();
      return this;
    }

    private int buildingCode_ ;
    /**
     * <code>required int32 building_code = 3;</code>
     * @return Whether the buildingCode field is set.
     */
    @java.lang.Override
    public boolean hasBuildingCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 building_code = 3;</code>
     * @return The buildingCode.
     */
    @java.lang.Override
    public int getBuildingCode() {
      return buildingCode_;
    }
    /**
     * <code>required int32 building_code = 3;</code>
     * @param value The buildingCode to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingCode(int value) {
      bitField0_ |= 0x00000004;
      buildingCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 building_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildingCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      buildingCode_ = 0;
      onChanged();
      return this;
    }

    private float salary_ ;
    /**
     * <code>required float salary = 4;</code>
     * @return Whether the salary field is set.
     */
    @java.lang.Override
    public boolean hasSalary() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required float salary = 4;</code>
     * @return The salary.
     */
    @java.lang.Override
    public float getSalary() {
      return salary_;
    }
    /**
     * <code>required float salary = 4;</code>
     * @param value The salary to set.
     * @return This builder for chaining.
     */
    public Builder setSalary(float value) {
      bitField0_ |= 0x00000008;
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required float salary = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalary() {
      bitField0_ = (bitField0_ & ~0x00000008);
      salary_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object department_ = "";
    /**
     * <code>required string department = 5;</code>
     * @return Whether the department field is set.
     */
    public boolean hasDepartment() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string department = 5;</code>
     * @return The department.
     */
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          department_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string department = 5;</code>
     * @return The bytes for department.
     */
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string department = 5;</code>
     * @param value The department to set.
     * @return This builder for chaining.
     */
    public Builder setDepartment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      department_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string department = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepartment() {
      bitField0_ = (bitField0_ & ~0x00000010);
      department_ = getDefaultInstance().getDepartment();
      onChanged();
      return this;
    }
    /**
     * <code>required string department = 5;</code>
     * @param value The bytes for department to set.
     * @return This builder for chaining.
     */
    public Builder setDepartmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      department_ = value;
      onChanged();
      return this;
    }

    private int floorNumber_ = 1;
    /**
     * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
     * @return Whether the floorNumber field is set.
     */
    @java.lang.Override public boolean hasFloorNumber() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
     * @return The floorNumber.
     */
    @java.lang.Override
    public autogeneratedProto.Employee.FLOOR getFloorNumber() {
      @SuppressWarnings("deprecation")
      autogeneratedProto.Employee.FLOOR result = autogeneratedProto.Employee.FLOOR.valueOf(floorNumber_);
      return result == null ? autogeneratedProto.Employee.FLOOR.FLOOR_1 : result;
    }
    /**
     * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
     * @param value The floorNumber to set.
     * @return This builder for chaining.
     */
    public Builder setFloorNumber(autogeneratedProto.Employee.FLOOR value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      floorNumber_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloorNumber() {
      bitField0_ = (bitField0_ & ~0x00000020);
      floorNumber_ = 1;
      onChanged();
      return this;
    }

    private int cafeteriaCode_ ;
    /**
     * <code>optional int32 cafeteria_code = 7;</code>
     * @return Whether the cafeteriaCode field is set.
     */
    @java.lang.Override
    public boolean hasCafeteriaCode() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 cafeteria_code = 7;</code>
     * @return The cafeteriaCode.
     */
    @java.lang.Override
    public int getCafeteriaCode() {
      return cafeteriaCode_;
    }
    /**
     * <code>optional int32 cafeteria_code = 7;</code>
     * @param value The cafeteriaCode to set.
     * @return This builder for chaining.
     */
    public Builder setCafeteriaCode(int value) {
      bitField0_ |= 0x00000040;
      cafeteriaCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cafeteria_code = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCafeteriaCode() {
      bitField0_ = (bitField0_ & ~0x00000040);
      cafeteriaCode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:autogeneratedProto.Employee)
  }

  // @@protoc_insertion_point(class_scope:autogeneratedProto.Employee)
  private static final autogeneratedProto.Employee DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new autogeneratedProto.Employee();
  }

  public static autogeneratedProto.Employee getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Employee>
      PARSER = new com.google.protobuf.AbstractParser<Employee>() {
    @java.lang.Override
    public Employee parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Employee(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Employee> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Employee> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public autogeneratedProto.Employee getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

