// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package autogeneratedProto;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autogeneratedProto.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 employee_id = 2;</code>
   * @return Whether the employeeId field is set.
   */
  boolean hasEmployeeId();
  /**
   * <code>required int32 employee_id = 2;</code>
   * @return The employeeId.
   */
  int getEmployeeId();

  /**
   * <code>required int32 building_code = 3;</code>
   * @return Whether the buildingCode field is set.
   */
  boolean hasBuildingCode();
  /**
   * <code>required int32 building_code = 3;</code>
   * @return The buildingCode.
   */
  int getBuildingCode();

  /**
   * <code>required float salary = 4;</code>
   * @return Whether the salary field is set.
   */
  boolean hasSalary();
  /**
   * <code>required float salary = 4;</code>
   * @return The salary.
   */
  float getSalary();

  /**
   * <code>required string department = 5;</code>
   * @return Whether the department field is set.
   */
  boolean hasDepartment();
  /**
   * <code>required string department = 5;</code>
   * @return The department.
   */
  java.lang.String getDepartment();
  /**
   * <code>required string department = 5;</code>
   * @return The bytes for department.
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
   * @return Whether the floorNumber field is set.
   */
  boolean hasFloorNumber();
  /**
   * <code>required .autogeneratedProto.Employee.FLOOR floor_number = 6;</code>
   * @return The floorNumber.
   */
  autogeneratedProto.Employee.FLOOR getFloorNumber();

  /**
   * <code>optional int32 cafeteria_code = 7;</code>
   * @return Whether the cafeteriaCode field is set.
   */
  boolean hasCafeteriaCode();
  /**
   * <code>optional int32 cafeteria_code = 7;</code>
   * @return The cafeteriaCode.
   */
  int getCafeteriaCode();
}
